nuscenes_python/nuscenes_utils/data_classes.py
nuscenes_python/nuscenes_utils/geometry_utils.py

The purpose of this PR is to remove support for pointcloud filetypes that are not needed by nuScenes.

Remove PCD Support

---

README.md
instructions.md

- Modified links
- Minor reformatting

Links now pointing to www.nuscenes.org

---

README.md

Added changelog and FAQs to readme

Added changelog and FAQs to readme

---

README.md
setup.py

This PR:
- Adds a setup.py for package installation via pip.
- Fixes a broken link in the readme.

setup.py for PIP packages

---

python-sdk/nuscenes/utils/data_classes.py

Fixes https://github.com/nutonomy/nuscenes-devkit/issues/34

Added missing Dict import

---

python-sdk/nuscenes/utils/data_classes.py

Addresses https://github.com/nutonomy/nuscenes-devkit/issues/33
Fixed typing to be compatible where future annotations package cannot be loaded

Typing fix

---

python-sdk/nuscenes/eval/eval_utils.py
python-sdk/nuscenes/eval/nuscenes_eval.py

Backport changes for master branch.
Addresses https://github.com/nutonomy/nuscenes-devkit/issues/40

Same attr changes as in 94657906623d9b67bd66f8fe3ed1efa81eb104f0

---

python-sdk/nuscenes/eval/nuscenes_eval.py

See https://github.com/nutonomy/nuscenes-devkit/issues/43

Fix incorrect reference to member nusc

---

python-sdk/nuscenes/eval/eval_utils.py

Shift (pi, 2*pi] to (0, pi] in correct way.

Fix yaw_diff calculation

---

python-sdk/nuscenes/eval/README.md
python-sdk/nuscenes/eval/nuscenes_eval.py

Added a disclaimer to the nuScenes eval readme.

Added disclaimer

---

python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py
python-sdk/nuscenes/utils/data_classes.py
python-sdk/nuscenes/utils/geometry_utils.py
python-sdk/nuscenes/utils/map_mask.py

Simple PR that updates the style to the latest format (more to follow after eval PR is merged).
It also makes sure that PointCloud parameters can be overridden as expected.

Style update

---

python-sdk/nuscenes/eval/detection/loaders.py
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/tests/test_nuscenes.py
python-sdk/nuscenes/utils/splits.py

v0.2 CI preparation.

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/detection/config.json
python-sdk/nuscenes/eval/detection/constants.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py

This implements the discussion yesterday such that the final detection score always includes all TP scores.

Simplified final score

---

python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/eval/detection/utils.py

This PR came about as I re-enabled the regression tests on the DB. It exposed some carelessness on handling corner-cases as well as (at least) one bug. This PR fixes those issues.
I think we can merge this quickly and then move into writing unit-tests.

Catching corner cases and "algo.py" cleanup.

---

python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_utils.py
python-sdk/nuscenes/eval/detection/utils.py

Here are few unittests for utils.py and algo.py.
I'll check for more tomorrow.

Some unittests for algo.py and util.py

---

README.md
instructions.md
setup/installation.md

- Added back `instructions.md` after popular demand, but moved it to `setup` folder.
- Updated description of debris class.
- Tuned main README.

Updated readme files

---

python-sdk/nuscenes/nuscenes.py

Now the default looks like this:

Added color options for render_egoposes_on_map

---

python-sdk/nuscenes/eval/detection/constants.py
python-sdk/nuscenes/eval/detection/render.py

This PR proposes the updates to plots as per our meeting.
For paper, we can probably use `Constr. Veh.` for `construction_vehicle`, but in the dev-kit, we can leave it as `Construction Vehicle`.
With these changes, The AP summary plot would look like this. 
The old plot looks like this

Summary AP plot update

---

setup/setup.py

Change setup.py to make the pip package.

Preparation for pip package v1.0.0

---

python-sdk/nuscenes/eval/detection/README.md

This PR updates the detection evaluation README. Main changes are
- Update the text related to metrics to use language from the paper.
- Added a "challenges" section and put it up front.
- Fixed hyperlinks
- Cleaned up text throughout.

Updated eval/detection/readme.md

---

README.md

This adds paper references to the main Readme.

Add paper references

---

python-sdk/nuscenes/eval/detection/data_classes.py

EvalBoxes bug quick fix

---

faqs.md
python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/evaluate.py
python-sdk/nuscenes/eval/detection/loaders.py
python-sdk/nuscenes/eval/detection/render.py

Added link to eval server (still pending admin approval)
Added further clarifications to the challenge rules
Print AP as decimal and averaged over classes
Check for old results format
More meaningful error messages

nuScenes challenge rules, eval server link and more robust error handling

---

python-sdk/nuscenes/eval/detection/README.md

Following feedback from our users, we clarify the definitions and rules of the three challenge tracks.

Clarified the definitions and rules of the three challenge tracks

---

python-sdk/nuscenes/eval/detection/tests/test_evaluate.py

This PR fixes a broken unit test due to new result format in https://github.com/nutonomy/nuscenes-devkit/pull/115.

Adapted test to updated submission format

---

setup/Jenkinsfile
setup/docker.yaml

- fix Jenkins job from periodic failures
- run stages in parallel

Dv 530/update jenkins job

---

python-sdk/nuscenes/nuscenes.py

render_instance with all parameters adopted from render_annotation

improved version of render_instance 

---

setup/Jenkinsfile
setup/test_tutorial.sh

Dv 720/fix jenkins failure

---

python-sdk/nuscenes/eval/detection/README.md

Made it clearer how to participate in the detection task, that the eval server is open all year and that the challenge is over.

Added notes that CVPR challenge is over

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/tracking/README.md

Follow-up of https://github.com/nutonomy/nuscenes-devkit/pull/220.

Improve tracking readme

---

python-sdk/nuscenes/eval/tracking/algo.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/loaders.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py

This PR illustrates usage of py-motmetrics for evaluation

Using py-motmetrics for evaluation

---

python-sdk/nuscenes/eval/tracking/loaders.py

Used `defaultdict` to make code for loading tracks leaner and cleaner. Passes all tests. Feel free to reject if you prefer explicit initialization.

Used defaultdict to simplify loaders

---

python-sdk/nuscenes/eval/common/data_classes.py
python-sdk/nuscenes/eval/common/loaders.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/tracking/algo.py
python-sdk/nuscenes/eval/tracking/data_classes.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/loaders.py
python-sdk/nuscenes/eval/tracking/mot.py
python-sdk/nuscenes/eval/tracking/render.py
python-sdk/nuscenes/eval/tracking/utils.py

This PR implements a BEV visualization for the scenes and objects. It exposes the functionality to the user to help debugging and subjective assessment of tracking performance. User needs to input the list of classes to visualize. Example usage
```
python evaluate.py result_path --output_dir output_path --render_classes car bus 
```
Example output: 
The output is generated from vehicle coordinate system. The tracking boxes are augmented with vehicle based coordinates in order to achieve this effect. 
The black boxes represent ground truth and colored boxes are predictions where each prediction is associated with a unique color. The switches are highlighted by changing front and the back border of the object to red.

Tracking eval BEV visualization

---

python-sdk/nuscenes/eval/tracking/tests/scenarios.py
python-sdk/nuscenes/eval/tracking/tests/test_algo.py

This PR implements a simple test structure to make scenario testing easier. It illustrates the usage on few critical cases.

Implement edge case test scenarios

---

README.md
python-sdk/nuscenes/eval/tracking/README.md
setup/setup.py

This PR adds explanations to the readme on how to use [nuScenes with Yonohub](https://medium.com/@ahmedmagdyattia1996/using-yonohub-to-participate-in-the-nuscenes-tracking-challenge-338a3e338db9).

Instructions how to use Yonohub

---

setup/Jenkinsfile

move job to new Jenkins && switch cloud
MERGE AFTER Dec 10

Switch to new cloud

---

python-sdk/nuscenes/map_expansion/map_api.py

This PR fixes the indexing bug in https://github.com/nutonomy/nuscenes-devkit/issues/282 . We reran the tutorial and saw no significant difference.

Fix _is_line_record_in_patch bug, addresses #282

---

python-sdk/nuscenes/eval/predict/README.md

@emwolff @holger-nutonomy This is the first draft of the README explaining the rules of the predict challenge. Please review!

Predict Challenge README

---

python-sdk/nuscenes/map_expansion/map_api.py

PR for adding lane connectivity with a clean git history

Add Lane Connectivity Clean

---

python-sdk/nuscenes/map_expansion/arcline_path_utils.py
python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/nuscenes/map_expansion/tests/test_arcline_path_utils.py

Adds extra spline utility functions with a cleaner commit history

Extra spline utilities clean

---

python-sdk/nuscenes/eval/predict/baseline_model_inference.py
python-sdk/nuscenes/predict/models/physics.py
python-sdk/nuscenes/predict/tests/test_physics_models.py

Fix a bug in the constant velocity heading baseline (it was calling the wrong kinematics function) and added unit tests. Also fixed a typo in the docstring.

CV Baseline Bug

---

python-sdk/nuscenes/can_bus/README.md

This PR improves the readability of the CAN bus expansion readme.

Improve readability of CAN bus readme

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

This PR adds a logo to prediction README.

Adding logo to prediction README

---

python-sdk/nuscenes/eval/prediction/README.md

Removes hanging exclamation point

Remove extra exclamation point from predict readme logo

---

python-sdk/nuscenes/prediction/models/covernet.py
python-sdk/nuscenes/prediction/tests/test_covernet.py

Changing the distance function used by CoverNet.

Implementing mean pointwise l2 distance

---

README.md
python-sdk/tutorials/prediction_tutorial.ipynb

Show how to do inference with the CoverNet model.

Adding information to the tutorial on doing inference with CoverNet

---

python-sdk/nuscenes/map_expansion/map_api.py

This PR addresses the refactoring of the `render_map_in_image()` method, as suggested in #358.

Refactor render_map_in_image, addresses #358

---

python-sdk/tutorials/prediction_tutorial.ipynb

- Add dataroot to prediction tutorial
- Fix typo

Add dataroot to prediction tutorial, see #382

---

README.md

This PR fixes two broken links.

Fix broken tutorial links

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/prediction/README.md

This PR links to the EvalAI page for prediction.

Link to EvalAI server

---

README.md

We accidentally reported an issue, that turned out to be due to faulty code of a user, rather than a real issue in the dataset. This PR removes it.

Remove false known issue

---

python-sdk/nuscenes/lidarseg/lidarseg_utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/utils/color_map.py
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- Include rendering of lidarseg videos with bboxes.
- Minor refactoring and renaming of methods and method arguments.
- Update the colormap for the various classes
- Create a single colormap for both nuScenes and nuScenes lidarseg

Enable bboxes to be plotted with lidarseg

---

README.md
setup/setup.py

Increment version number and add a summary of v1.0.8 and v1.0.9.

Increment version number

---

docs/instructions_lidarseg.md
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- Add the markdown for the annotators' instructions
- Amend the tutorial's introduction for more clarity

Add lidarseg annotation instructions, update lidarseg tutorial intro

---

README.md
docs/instructions_nuimages.md
python-sdk/nuimages/nuimages.py
python-sdk/nuimages/scripts/render_rare_classes.py
python-sdk/nuimages/tests/test_attributes.py
python-sdk/nuimages/tests/test_foreign_keys.py

This PR addresses misc feedback from the nuScenes v2.0 alpha testing.

nuScenes v2.0 alpha

---

README.md
docs/installation.md
docs/instructions_nuimages.md
python-sdk/nuimages/nuimages.py
python-sdk/nuimages/scripts/render_rare_classes.py
python-sdk/nuimages/tests/test_attributes.py
python-sdk/nuimages/tests/test_foreign_keys.py
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- The inconsistencies between the classes described in the text and the classes used in the code snippets
- Add tip for matplotlib to use backend TKAgg or MacOSx if an exception occurs when doing lidarseg-related rendering

Address comments from nuScenes-lidarseg alpha testing

---

README.md
python-sdk/tutorials/nuimages_tutorial.ipynb

- Fix some broken links in the readme and nuImages tutorial

Fix links in readme and nuImages tutorial

---

python-sdk/tutorials/nuimages_tutorial.ipynb
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb
python-sdk/tutorials/nuscenes_tutorial.ipynb

- Update links in the colab tutorials for nuImages, nuScenes and nuScenes-lidarseg

Update links in colab tutorials

---

python-sdk/nuscenes/eval/lidarseg/README.md

- Set out the rules and details for the nuScenes-lidarseg challenge

nuScenes lidar segmentation challenge

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md

Add an announcement for the 2020 NeurIPS detection challenge.

Add NeurIPS 2020 detection challenge

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

This PR updates some outdated links.

Update EvalAI links to new domain

---

README.md
setup/setup.py

Version 1.1.1

---

python-sdk/nuscenes/eval/lidarseg/validate_submission.py

- Get the filename of the ground truth from nusc class
- Fix a print statement

Fix some typos in validate_submission for lidarseg challenge

---

python-sdk/nuscenes/eval/lidarseg/README.md

- Insert EvalAI link for nuScenes lidarseg challenge

Insert EvalAI link for nuScenes lidarseg challenge

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

- Add that participants need to submit certain info for display on leaderboard
- Add lidarseg challenge deadline

Add that participants need to submit certain info for display on leaderboard, add lidarseg challenge deadline

---

python-sdk/nuscenes/eval/lidarseg/validate_submission.py

- Give nuScenes-lidarseg challenge participants an option to zip up their results folder

Give nuScenes-lidarseg challenge participants an option to zip up their results folder

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/lidarseg/render.py
python-sdk/nuscenes/eval/lidarseg/validate_submission.py

- Add the results for the 5th AIDO challenges (lidar segmentation and detection)
- Amend the `help` message for `--zip_out` in `validate_submisison.py`
- In `render_stratified_per_class_metrics` of `render.py`:
- make the default for `dpi` as 250 in order to produce plots of higher resolution by default
- hide the top and right splines of the plot to prevent the numbers from being cut off
- In `render_stratified_overall_metrics` of `render.py`
-  - hide the top and right splines of the plot to prevent the numbers from being cut off

Results for 5th AIDO challenges

---

python-sdk/nuscenes/eval/detection/README.md

This corrects the Noah result from 69.7% to 69.0% NDS.

Typo in detection results

---

python-sdk/nuscenes/scripts/export_instance_videos.py

For more detailed instructions please see:
https://github.com/EricWiener/nuscenes-instance-videos
Please see issue #512

Added script to generate videos of nuScene instances

---

python-sdk/nuimages/nuimages.py

Fixes a wrong assertion, see https://github.com/nutonomy/nuscenes-devkit/issues/559.

Fix wrong assertion #559

---

README.md
setup/setup.py

This PR updates the version of the pip package so it can be exported to pypi.

Update pip version to 1.1.3

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

- Add descriptions for the nuScenes challenges to be held at ICRA 2021

Announcements for nuScenes challenges at ICRA 2021

---

python-sdk/nuscenes/utils/data_classes.py
python-sdk/nuscenes/utils/tests/test_data_classes.py

This PR fixes a bug reported in https://github.com/nutonomy/nuscenes-devkit/issues/588.
It also adds a test to check for future regression.

Add radar dtype bugfix and test, addresses #588

---

setup/setup.py

Bump pip version to 1.1.5

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

Add results for ICRA 2021

---

README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/lidarseg/evaluate.py
python-sdk/nuscenes/eval/lidarseg/render.py
python-sdk/nuscenes/eval/lidarseg/utils.py
python-sdk/nuscenes/eval/panoptic/README.md
python-sdk/nuscenes/eval/panoptic/evaluate.py
python-sdk/nuscenes/eval/panoptic/panoptic_seg_evaluator.py
python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py
python-sdk/nuscenes/eval/panoptic/utils.py
python-sdk/nuscenes/lidarseg/lidarseg_utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/panoptic/generate_panoptic_labels.py
python-sdk/nuscenes/panoptic/panoptic_utils.py
python-sdk/nuscenes/utils/data_classes.py
python-sdk/nuscenes/utils/data_io.py
python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb
setup/Jenkinsfile

- Add panoptic ground truth generation script.
-  Add nuScenes-panoptic eval code for panoptic segmentation and muliti-object panoptic tracking.
-  nuScenes-panoptic tutorial added on top of nuScenes-lidarseg tutorial.
-  Panoptic challenge announcement.

nuScenes-panoptic v1.0 release

---

python-sdk/nuscenes/eval/panoptic/baselines.py

- Make generating and evaluation of panoptic baselines parallel

Make generating and evaluation of panoptic baselines parallel

---

README.md
python-sdk/nuscenes/eval/panoptic/evaluate.py
python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py
setup/setup.py

Add MOTSA, sMOTSA and MOTSP metrics for panoptic tracking evaluation.

Add MOTSA metrics for panoptic tracking

---

python-sdk/nuscenes/eval/panoptic/README.md
python-sdk/nuscenes/eval/panoptic/baselines.py
python-sdk/nuscenes/eval/panoptic/evaluate.py
python-sdk/nuscenes/eval/panoptic/get_panoptic_from_seg_det_or_track.py
python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py
python-sdk/nuscenes/eval/panoptic/utils.py
python-sdk/nuscenes/panoptic/generate_panoptic_labels.py
python-sdk/nuscenes/panoptic/panoptic_utils.py
python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb

- Update Panoptic Eval readme on the evaluation server and primary ranking metrics.

Update Panoptic nuScenes Eval readme

---

python-sdk/nuscenes/eval/tracking/README.md

Update the company name in the readme from Aptiv to Motional.

Change company name

---

python-sdk/nuscenes/map_expansion/arcline_path_utils.py

- Fix hardcoded resolution_meters in project_pose_to_lane (reported in https://github.com/nutonomy/nuscenes-devkit/issues/683)

Fix hardcoded resolution_meters in project_pose_to_lane

---

python-sdk/nuscenes/eval/tracking/algo.py

- Fix bug when padding values with nans for unachieved recall thresholds

Fix bug when padding values with nans for unachieved recall thresholds

---

README.md
setup/setup.py

Bump pip version to 1.1.10

---

setup/setup.py

Update license in `setup.py` to Apache 2.0

Update license in setup.py to Apache 2.0

---

python-sdk/nuscenes/eval/detection/render.py

[feat] Make an option whether or not to render with the legend
| display_legend <br> ``True`` |display_legend <br> ``False`` |
|--|--|
|![image](https://github.com/nutonomy/nuscenes-devkit/assets/29084184/c7b94c7c-a0cf-4541-8f90-09ad6c3ca15a)|![image](https://github.com/nutonomy/nuscenes-devkit/assets/29084184/cb0706ea-0efc-4888-8c03-fa6db2135ab1)|

[feat] Add a legend for the "gt box" and "est box" in the visualization function

---

setup/Jenkinsfile

Update ClaimName in CI pipeline configuration

Update ClaimName in CI

---

README.md

Update Motional logos in repository README

Update Motional logos in README.md
