python-sdk/examples/export_pointclouds_as_obj.py
python-sdk/nuscenes_utils/data_classes.py
python-sdk/nuscenes_utils/nuscenes.py

This PR adds functionality to:
- Parse RADAR files (previously only LIDAR was supported).
- Export the aggregated point cloud of an entire scene.

Radar file parser and point cloud export script

---

python-sdk/nuscenes/utils/map_mask.py

This PR simplifies the MapMask considerably. I deleted `self._distance_mask`, `self._binary_mask` and created a function `self.dilate_mask()`. This allows the user control on whether he wants to dilate the mask or not. Also, we don't store three huge binary masks in memory.

Simpler MapMask

---

python-sdk/nuscenes/eval/nuscenes_eval.py

Doing the same here, so that run_eval() works even when not called as __main__. Now member is used instead of global var.

 Fix incorrect reference to member output_dir

---

python-sdk/nuscenes/eval/nuscenes_eval.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/utils/map_mask.py
python-sdk/nuscenes/utils/tests/test_map_mask.py
python-sdk/tutorial.ipynb
requirements.txt

This cleans up the MAP API.
1) Remove accumulative dilation behavior.
2) Uses caching library
3) Renames `get_pixel` to `to_map_coord`. This now calls `transform_matrix` instead of re-implementing logic.
4) Supports different resolution on init. This helps clean up the Explorer code.
TODO:

Cleaned up map API. Note breaking changes.

---

python-sdk/nuscenes/eval/eval_utils.py
python-sdk/nuscenes/eval/nuscenes_eval.py

This does three changes to the evaluation code:
1. switch distance from xyz to xy as is used elsewhere in evaluation
2. ensure that when an extra recall of zero is added that the other metrics are also updated
3. return the maximum error when the minimum recall is not achieved

Evaluation Fixes

---

Dockerfile
Jenkinsfile

During each push to remote, `python -m unittest` is executed inside of a Docker container.
The result of the pipeline is published to the Slack channel **nuscenes-ci**.
The output of the Jenkins pipeline can be viewed at this link: https://jenkins.nutonomy.team/job/nuscenesCI/job/continuous-integration/3/

Continuous integration

---

python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/loaders.py
python-sdk/nuscenes/eval/detection/tests/test_main.py

I think we should use the ego vehicle pose when we calculate `EvalBox.ego_dist`. Feels more intuitive than picking the LIDAR sensor (even if, arguably, the LIDAR is closer to the center than the ego vehicle origin itself). This also helped clean up the code a bunch ;)

Changes to calculating distance from ego_vehicle

---

python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/utils/splits.py

This PR adds the mini-train (8 scenes) and mini-val (2 scenes) splits.
Furthermore it modifies the logic of the `create_splits_scenes` and `create_splits_logs` functions. This makes the code more flexible and allows to quickly lookup which split a scene is in without loading the NuScenes database.
Note: The method signatures changed, now `create_splits_logs` requires a NuScenes object and `create_splits_scenes` does not.

Mini splits and modified split logic

---

python-sdk/nuscenes/__init__.py
python-sdk/nuscenes/eval/detection/__init__.py
python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/render.py
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/eval/detection/tests/test_utils.py
python-sdk/nuscenes/eval/detection/utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/scripts/assert_download.py
python-sdk/nuscenes/scripts/export_egoposes_on_map.py
python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py
python-sdk/nuscenes/scripts/export_scene_videos.py
python-sdk/nuscenes/tests/test_nuscenes.py
python-sdk/nuscenes/utils/geometry_utils.py
python-sdk/nuscenes/utils/splits.py
python-sdk/nuscenes/utils/tests/test_geometry_utils.py
requirements.txt

This PR does three things:
1. ~~Move quaternion_yaw out of eval utils to general utils~~
2. Eliminate quaternion_slerp now that pyquaternion is fixed
3. Add some shortcuts to common classes
If (3) is not desired, we can revert commit 75c42f9

Misc Reorg

---

python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_data_classes.py
python-sdk/nuscenes/eval/detection/tests/test_utils.py
python-sdk/nuscenes/eval/detection/utils.py

This PR discards orientation errors for cones. It also measures orientation errors for barriers on a 180 degree period. It further fixed a bug in how we calculate the TP scores. The TP error is now the average across classes. This is in native interpretable units and is what will go on the leaderboard. The score is then simply `max(0, 1-mean_class_tp_err)`.

Orientation handling and asserts

---

Jenkinsfile
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/tests/test_nuscenes.py
test_mini_split.sh

In this PR, we enable unit tests in which instances of `NuScenes` with version argument `v1.0-mini` are created.  A separate Docker image containing the data dependencies corresponding to `nuscenes/v1.0-mini` has been pushed to registry https://registry-local.nutonomy.team:5000/nuscenes/mini_split_data. 
Inside of the Jenkins pipeline, the aforementioned Docker image is pulled and then a container containing the `mini_split` data is created.  This container is used to create a Docker volume which can then be mounted into the container containing the `nuscenes-devkit` test code. 
Snippet from Jenkins pipeline corresponding to reading from `mini_split`  : 
`
Successfully tagged test_mini_split:latest
0%|          | 0/162 [00:00<?, ?it/s]
25%|██▍       | 40/162 [00:00<00:00, 397.89it/s] …

Integrate mini_split into continuous integration

---

Dockerfile
README.md
python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/utils/data_classes.py
python-sdk/nuscenes/utils/geometry_utils.py
setup.py

* Removed typing that were only suitable to only Python3.6 onwards
* Removed the future import
* Tutorial and unittests ran well
* Also includes minor cleanups to reduce PyCharm warnings
* WIP because will wait for other PRs to be merged in to again check compatibility.

Make nuScenes compatible to Python3.5/Python3.6

---

python-sdk/nuscenes/utils/splits.py

This updates create_splits_logs to work with the new format of multiple databases

Update create_splits_logs to new database versions

---

python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/utils/data_classes.py

Hi guys,
found myself really missing this field as I was doing some mining, so I added it. Thoughts?

added token field to Box class

---

python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_main.py
python-sdk/nuscenes/eval/detection/tests/test_utils.py
python-sdk/nuscenes/eval/detection/utils.py

This adds some simple unit tests to check the correctness of the AP calculation. Modified the AP calculation to exclude the bin that is equal to `min_recall` value as discussed in the office. 
Now the `calc_ap` method returns nan value for `min_recall = 1.0` as we calculate average of precisions corresponding to `recall>min_recall` instead of `recall>=min_recall`.
I also cleaned up some old tests to avoid PEP8 warnings.

Simple Unittests for AP calculation

---

README.md
python-sdk/nuscenes/eval/detection/README.md

Changes to general readme and detection readme:
- Changed outdated download instructions as files are structured differently.
- Removed FAQ as most of it does not relate to the full release.
- Removed disclaimer
- Removed annotation frequencies as these are also on the homepage.
- Renamed weighted sum to nuScenes Detection Score.

Readme update

---

python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/main.py
python-sdk/nuscenes/eval/detection/render.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_main.py

This PR adds some unit tests to check the correctness of the TP metric calculation. 
I had to change the regression test score (and one other regression test) because of a minor bug fix in `calc_tp` method.
Please have a look and let me know if anything doesn't make sense, thanks.

Unittests for true positive error metrics calculation

---

python-sdk/nuscenes/utils/map_mask.py

Now that the new maps are stored as [0, 255], we don't need the explicit conversion. This PR simply gets rid of them. I have checked the `render_egoposes_on_map()` method and it works the same as before.

Removed legacy map binarize

---

python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py
setup/requirements.txt

This PR adds the script to produce 2d annotations that are **re-projected from our 3d boxes** in the form of a .json file.
The details of the post processing steps are as follows:
1. Retrieve the corners of the 3D bounding box that is in front of the camera.
2. Used the convex hull of the corners.
3. Retrieve the intersecting polygons.
4. Bounding box corners is decided from the intersecting polygons
Sample renderings of the re-projected 2d annotations:

Export 2d annotations

---

python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/tests/test_data_classes.py

This adds a deserialize method to DetectionMetrics, which allows rendering to occur at a later time. This also updates the DetectionMetrics.serialize method to include the configuration.

Add deserialize to DetectionMetrics

---

python-sdk/nuscenes/eval/detection/config.py
python-sdk/nuscenes/eval/detection/evaluate.py
python-sdk/nuscenes/eval/detection/tests/test_evaluate.py

This PR revives the config factory for greater convenience when a user wants to use a provided config (e.g. cvpr_2019). Previously the user would need to figure out the location of the config file.

Re-added simple config factory

---

python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py
python-sdk/nuscenes/scripts/export_kitti.py
python-sdk/nuscenes/utils/kitti.py

This PR addresses https://github.com/nutonomy/nuscenes-devkit/issues/156 by adding 2d boxes to the KITTI output. It also enables rendering the 2d annotatons:
```
python export_kitti.py render_kitti --nusc_kitti_dir ~/nusc_kitti --render_2d False
```
Furthermore we add a disclaimer to the 3d-2d conversion script that the resulting boxes are generally not tight.
Below are some example of 2d and 3d boxes:

nuScenes KITTI 2d boxes

---

python-sdk/nuscenes/eval/detection/evaluate.py

Currently, teams that submit to the nuScenes evaluation server can only see metrics averaged over classes. This PR prints the per-class metrics to stdout so users can get immediate feedback.

Print per class metrics after evaluation

---

python-sdk/nuscenes/nuscenes.py

Addresses #167 by loading the `image_annotations` table if it is available.
This is done purely for convenience and has no impact if the table is not available.

Loading image_annotations table if available

---

python-sdk/nuscenes/nuscenes.py
schema.md

This PR alleviates #175 by filtering points with a distance below 10cm. However, it does not resolve the underlying issue if one tries to render pointclouds in the camera that are out of sync.
Furthermore, I added some clarifications that the provided ego_pose has no meaningful z component.

Pointcloud projection issue workaround

---

python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py

As the issue in https://github.com/nutonomy/nuscenes-devkit/issues/176 seems resolved, this PR only contains a few cleanups and a new parameter to only export a subset of images.

Cleanup of the export_2d script

---

python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/nuscenes/map_expansion/map_demo.ipynb

This PR fixes a bug reported by a user. The singapore-queenstown map has at least one line with 0 nodes. This causes the `render_record` function to crash.
Please file an issue if you find any other use cases where this can cause problems.

Map workaround for singapore-queenstown

---

python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/nuscenes/map_expansion/map_demo.ipynb
python-sdk/nuscenes/utils/geometry_utils.py
python-sdk/tutorial.ipynb

This PR addresses the previously requested feature to project semantic map layers into the camera image view. The main difficulty here is to figure out what to do with polygons where some points are behind the camera. Note that the projections are not always accurate as the localization is in 2d.
An example was added to the tutorial.
A video with some renderings can be found at: https://www.youtube.com/watch?v=wUBdMrnL6BU&feature=youtu.be

Project map to image, resolves #188

---

setup/installation.md

In https://github.com/nutonomy/nuscenes-devkit/issues/155 analog-cbarber proposed a method to install nuscenes-devkit as a Conda distribution package, rather than a PIP package. This required a `post-link hack to install pyquaternion using pip`. Therefore it was decided not to merge these changes to master. Nevertheless we want to refer interested parties to this issue for reference.

Added link to the Conda distribution issue, closes #155

---

python-sdk/nuscenes/nuscenes.py

I added optional rendering of extra information about the annotation below the CAMERA view.
[example image](https://i.ibb.co/nPRp96D/9cba9cd8af85487fb010652c90d845b5-1538448747047643.png)
I set the default value four times to `False`:
[here](https://github.com/MartinHahner88/nuscenes-devkit-fork/blob/f51d5d1316ebf7cd9249107da7a1f5fbd3d0e70c/python-sdk/nuscenes/nuscenes.py#L403), [here](https://github.com/MartinHahner88/nuscenes-devkit-fork/blob/f51d5d1316ebf7cd9249107da7a1f5fbd3d0e70c/python-sdk/nuscenes/nuscenes.py#L408), [here](https://github.com/MartinHahner88/nuscenes-devkit-fork/blob/f51d5d1316ebf7cd9249107da7a1f5fbd3d0e70c/python-sdk/nuscenes/nuscenes.py#L817) and [ here](https://github.com/MartinHahner88/nuscenes-devkit-fork/blob/f51d5d1316ebf7cd9249107da7a1f5fbd3d0e70c/python-sdk/n …

render_annotation improved

---

python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py

Why:
* nuScenes database schema became useful format for organizing
large-scale datasets for autonomous driving.
* This changeset adds support for another nuScenes-formatted
dataset.
This change addresses the need by:
* Adding support for another dataset.
* Adding support for coloured rasterised maps.
* Adding an option for rendering vehicle-centered top-down views with
map in the background.

Support for another nuScenes-formatted dataset

---

python-sdk/nuscenes/eval/detection/loaders.py
python-sdk/nuscenes/utils/splits.py
setup/Dockerfile_3.6
setup/Dockerfile_3.7

For the upcoming detection challenge we want to enable users to train detector and tracker on separate training sets. This is entirely optional, but may help users to to avoid training their tracker on detections that are overfit to the training set. It is only relevant for learning-based approaches. 
**The existing train split is not modified.**

Split train set into train_detect and train_track

---

python-sdk/nuscenes/map_expansion/map_api.py

HI! I add options that you can choose options for render. It would be convenient for users who wanna render map that does not contain map description or ego pose black point.
I'll show examples below.
- original 
- delete ego pose black point
- delete ego pose black point and description

Add rendering options

---

python-sdk/nuscenes/map_expansion/map_api.py

Cleaned version of https://github.com/nutonomy/nuscenes-devkit/pull/223
Copying from that PR here:
I added rendering options. It would be convenient for users who want to render a map that does not contain map descriptions or ego poses.
I'll show examples below.
- Original 
- Hide ego poses
- Hide ego poses and description

Add rendering options (#223)

---

python-sdk/nuscenes/nuscenes.py

This PR changes the default settings for render_sample_data to use underlay_map and use_flat_vehicle_coordinates by default. It also prevents the user from attempting to underlay the map in the lidar view, which is not correct when the lidar vertical axis is not aligned with the global vertical axis.

Lyft compatibility default settings

---

python-sdk/nuscenes/nuscenes.py
python-sdk/tutorial.ipynb

This PR adds an option to `render_pointcloud_in_image` to visualize the lidar intensities.
This only works for lidar, not for radar.

Add option to render pointcloud intensities

---

python-sdk/nuscenes/nuscenes.py

Addresses the issue in https://forum.nuscenes.org/t/the-rendered-radar-image-is-not-accurate/167 .
When introducing the `use_flat_vehicle_coordinates` option, we retrieved the `cs_record` from the `sd_record` (radar), rather than reference `sd_record` (lidar). This went unnoticed as it did not affect the front radar, but only the other sides. Below is the corrected example with and without `use_flat_vehicle_coordinates` and `underlay_map`. Since the latter version without has not changed, everything seems to be correct. This was also validated in other samples and radars.

Fixed visualization bug where radar returns were not rotated

---

python-sdk/nuscenes/eval/common/loaders.py
python-sdk/nuscenes/eval/tracking/algo.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/loaders.py
python-sdk/nuscenes/eval/tracking/tests/test_algo.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py
python-sdk/nuscenes/eval/tracking/utils.py

This PR has 3 proposed cosmetic changes related to unit-tests:
- Made sure all tests run non-verbose. 
- Added `__init__.py` to tests folder to make sure it's indexed by `python -m unittest`. 
- Made it so that all tests run by default, not just the ones enumerated explicitly.

Made tracking unit-tests silent and executed by default

---

python-sdk/nuscenes/eval/tracking/README.md
python-sdk/nuscenes/eval/tracking/configs/tracking_nips_2019.json
python-sdk/nuscenes/eval/tracking/data_classes.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/tests/test_algo.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py
setup/requirements.txt

This PR includes various improvements to the nuScenes tracking evaluation code:
- Switch from 10-point to 40-point interpolation in evaluation, which can make up to 2.5% difference in AMOTA.
- Fix unit tests to work with any number of thresholds.
- Replace test with val results for the baselines.
- Remove lap solver which is slower and leads to issues with continuous integration.
- Optimize memory usage by freeing up NuScenes object.

nuScenes tracking evaluation improvements

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/tracking/README.md

- Add tracking eval server link.
- Adjust challenge deadline to December 9.
- Changed tracking challenge logo (uploaded soon).

Add tracking eval server link, adjust challenge deadline

---

python-sdk/nuscenes/eval/tracking/README.md
python-sdk/nuscenes/eval/tracking/metrics.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py

This PR removes the weighting factor (alpha = 0.2) from AMOTA.
This setting was applied to the nuScenes tracking challenge 2019 and the corresponding leaderboard (coming soon).

Remove weighting factor from AMOTA

---

python-sdk/nuscenes/eval/common/data_classes.py
python-sdk/nuscenes/eval/common/loaders.py
python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/data_classes.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_loader.py
python-sdk/nuscenes/eval/tracking/data_classes.py

For the tracking eval code we switched from storing ego_dist to storing ego_translation.
This PR does the same for the detection eval code and pushes some of the changes to the parent box class `EvalBox`. All tests pass.

Standardize ego_dist and ego_translation in detection and tracking eval code

---

setup/requirements.txt

In the following line we use Pandas with the `codes` keyword.
https://github.com/nutonomy/nuscenes-devkit/blob/d60d7b1caf9b336f11d036a2787194f387238407/python-sdk/nuscenes/eval/tracking/mot.py#L44 
This keyword was introduced in `v0.24`, while `py-motmetrics` only requires `v0.23`. Therefore this PR adds an explicit requirement on version `>=v0.24`.

Pandas minimum version requirement

---

python-sdk/nuscenes/map_expansion/map_api.py

In the map-expansion (`v1.0`) 46 scenes had ego-poses located off the drivable surface. The reason for this is that the scenes were located with slightly different map versions that may have local deformations. On 1/17/2020 we published `v1.1` which replaces the `singapore-onenorth` map and fixes the issues for 43/46 scenes. Three scenes remain that are slightly off the drivable surface and should not be used in conjunction with the map.
All new .json files have a `version` string to identify whether they are up-to-date. This PR merely prints a warning if the version is not up-to-date. Furthermore, it no longer prints a warning for the 43 scenes that are now fixed.

Update code to map version 1.1

---

python-sdk/nuscenes/map_expansion/map_api.py

This PR addresses an inconsistency in the Map API as discovered in https://github.com/nutonomy/nuscenes-devkit/issues/281. Despite rendering multiple plots, only a single axis is returned by the function.
The result was tested by rendering the map-tutorial.

Map API: Return all axes, not just one

---

python-sdk/nuscenes/predict/__init__.py
python-sdk/nuscenes/predict/helper.py
python-sdk/nuscenes/predict/tests/test_predict_helper.py
python-sdk/nuscenes/tests/test_predict_helper.py

Adds a PredictHelper class for getting the future and past of an agent given its instance token and one of its sample tokens. 
@holger-nutonomy, I've created a base branch for the challenge called `nuscenes-predict-challenge`. Let me know if this is ok with you.
How to test:
`nosetests nuscenes/tests`
FYI: @emwolff

Adding PredictHelper class and unit tests

---

python-sdk/nuscenes/eval/common/data_classes.py
python-sdk/nuscenes/eval/common/loaders.py
python-sdk/nuscenes/eval/detection/algo.py
python-sdk/nuscenes/eval/detection/evaluate.py
python-sdk/nuscenes/eval/detection/render.py
python-sdk/nuscenes/eval/detection/tests/test_algo.py
python-sdk/nuscenes/eval/detection/tests/test_evaluate.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/loaders.py
python-sdk/nuscenes/eval/tracking/metrics.py
python-sdk/nuscenes/eval/tracking/render.py
python-sdk/nuscenes/eval/tracking/tests/test_algo.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py
python-sdk/nuscenes/eval/tracking/utils.py
python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py
python-sdk/nuscenes/scripts/export_kitti.py
python-sdk/nuscenes/utils/data_classes.py
python-sdk/nuscenes/utils/kitti.py

This PR disables the slow unit tests from the tracking eval code (>100s runtime). This reduces the overall unit test runtime to 6s. Furthermore we rearrange all imports according to PEP 8.

Disable slow unittests

---

python-sdk/nuscenes/utils/data_classes.py
python-sdk/tutorial.ipynb

This simple PR adds a convenient function to disable all radar filters. This means that all radar returns (even ambiguous ones) are rendered. We also added an example to the tutorial.

Add an option to disable all radar filters

---

python-sdk/nuscenes/map_expansion/map_api.py

This PR fixes a bug in the map expansion, where the canvas_size was retrieved from the map_dims, rather than the patch_box, for the special case where canvas_size is set to None. The new behavior is that if a canvas_size is not provided, the rendering resolution is 10px/m.

Fix map mask scaling issue

---

python-sdk/nuscenes/utils/data_classes.py

This PR addresses issue https://github.com/nutonomy/nuscenes-devkit/issues/287. When aggregating multiple lidar sweeps, we first transform them to the reference frame, then remove the points close to the origin. The correct order is to remove the close points in the current sensor frame before moving them to the sensor frame at a different timestamp.
The difference can be seen below.
Before:
After:

Fix bug where points close to ego vehicle were filtered after transformation

---

python-sdk/nuscenes/eval/predict/baseline_model_inference.py
python-sdk/nuscenes/eval/predict/config.py
python-sdk/nuscenes/eval/predict/do_inference.py
python-sdk/nuscenes/predict/models/mtp.py
python-sdk/nuscenes/predict/models/physics.py
python-sdk/nuscenes/predict/tests/run_mtp.py
python-sdk/nuscenes/predict/tests/test_mtp.py
python-sdk/nuscenes/predict/tests/test_mtp_loss.py
python-sdk/nuscenes/tests/test_predict_helper.py
setup/requirements.txt

* Adds a baseline MTP model with Resnet, MobileNet backbones
* Converts models.py into a directory with physics.py and mtp.py
* Adds unit tests for mtp.py
How to test:
* Run unit tests `nosetests predict/tests` and `nosetests eval/predict/tests`
* The script `run_mtp.py` tests whether the mtp model can overfit on a single example (for 1 or two modes) with the cpu or gpu
@elenacorinagrigore Please verify the model implementation
@emwolff @holger-nutonomy your feedback is appreciated :smile:

Mtp baseline

---

setup/setup.py

This PR fixes a bug in the latest version of setuptools, where the file names inside `package_data` need to be an array. It only affects the creation of pip packages.

Fix bug in new version of setuptools

---

python-sdk/nuscenes/eval/tracking/mot.py
setup/requirements.txt

Addresses #299. Major changes in the new motmetrics version `1.2.0` break our tracking eval code. To ensure that the results of our tracking challenge do not change, we fix the version number to be `<= 1.1.3`.

Tracking eval - Fix motmetrics version

---

python-sdk/nuscenes/predict/input_representation/static_layers.py

The `make_representation` method in StaticLayerRasterizer used a resolution of 10 px / m to draw the canvas instead of using the parameter passed in by the user. This PR fixes that bug.

StaticLayerRasterizer uses right resolution parameter

---

python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/nuscenes/map_expansion/map_demo.ipynb

Modified version of https://github.com/nutonomy/nuscenes-devkit/pull/306. 
Lists all possible next roads for the current lane/road segment/road lane.
Additionally we provide a method to render the next roads.
Both functions have been added to the map tutorial.
**Note:** Using an outdated map now leads to an error, rather than a warning.
Below is an example:
```
import matplotlib.pyplot as plt
from nuscenes.map_expansion.map_api import NuScenesMap
nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name='singapore-onenorth')
x = 876
y = 1284
print(nusc_map.layers_on_point(x, y))
nusc_map.render_next_roads(x, y)
```
Returns 
```
{'drivable_area': 'c3e28556-b711-4581-9970-b66166fb907d', 'road_segment': '57416e99-8919-4a28-985b-033a16938243', 'road_block': '', 'lane': '', …
```

Get next roads function

---

instructions.md

This PR removes the firetruck class from the instructions. This class was removed from nuScenes, as it had only a handful of annotations. Addresses #328.

Removed firetruck from instructions

---

python-sdk/nuscenes/can_bus/can_bus_api.py
python-sdk/nuscenes/can_bus/tutorial.ipynb

- Rename and reorganize the `print_can_message_stats` function.
- Add more details to the tutorial, in particular render the vehicle speed vs. the wheel speed.

CAN bus refactor

---

README.md
python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/predict/README.md
setup/setup.py

- Increment devkit version to v1.0.7.
- Add information on the 2020 detection challenge.

Information on the 2020 detection challenge, pip version v1.0.7

---

python-sdk/nuscenes/map_expansion/map_api.py

When loading the map layers through the new map layers API, we can see that these reference coordinates originate from the bottom left, (ie: south-western) corner, instead of south-eastern.
A small change, but can cause some confusion.

Update map origins docstring in map_api.py

---

python-sdk/nuscenes/eval/prediction/README.md
setup/requirements.txt

- Relax the version requirements for torch and torchvision.
- Set a maximum pillow version as newer versions are not currently supported by torchvision.
- Merge in the changes from https://github.com/nutonomy/nuscenes-devkit/pull/339, as the torch l1 loss throws an exception (`RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #2 'target' in call to _thnn_l1_loss_forward`) - **wait for that PR to merge first**.

Relax pip package requirements

---

python-sdk/nuscenes/scripts/export_gps.py

For each scene pose, extract its corresponding GPS coordinates.
For example:
```
{
"scene-0001": [
{
"latitude": 1.2937032274375029,
"longitude": 103.79383855113322,
"timestamp": 1531883530449377
},
{
"latitude": 1.2937051818440861,
"longitude": 103.79383881598295,
"timestamp": 1531883530499678
},
...
```
This is based on the following [formula](https://www.movable-type.co.uk/scripts/latlong.html#dest-point). Which finds the coordinate of a point in 2d space, if given the distance and bearing to a reference coordinate.
Note: I am not sure if you are accepting PRs on this. But I found this useful and can add some additional value to this great dataset.
Please let me know if additional steps are needed for such PR.
Style-wise I tried to follow as closely as possible to other scripts in the …

Add script to export pose data

---

python-sdk/nuscenes/can_bus/README.md

See https://github.com/nutonomy/nuscenes-devkit/issues/371 for details. Correct the readme which confused left and right.

Flip left and right in can bus readme, addresses #371

---

python-sdk/nuscenes/prediction/tests/test_covernet.py

Hello,
This PR makes the nuscenes tests pass in a pytorch 1.2 / torchvision 0.4.0 environment.
To be specific, I ran `python -m unittest discover python-sdk` as well as `bash setup/test_tutorial.sh` in the nuscenes python 3.6 docker container with pytorch 1.2 and torchvision 0.4.0 and both passed with this PR.
I think it's significant that the changes to make this work are exclusively in the tests. Therefore, the nuscenes-devkit library itself is already compatible with pytorch 1.2. For users with projects that are locked into pytorch 1.2, it may be nice for them to know that they can use nuscenes-devkit.
Related to: https://github.com/nutonomy/nuscenes-devkit/issues/367

Make unit tests compatible with pytorch 1.2 + torchvision 0.4.0

---

python-sdk/nuscenes/eval/prediction/README.md

Clarifies that the report for the prediction challenge should be no more than 1-2 pages.

Clarifying report length for prediction challenge

---

python-sdk/nuscenes/eval/prediction/README.md

This PR specifies that the ICRA 2020 prediction challenge will be focused solely on vehicles.

Clarifying that the first challenge is focused solely on vehicles

---

README.md

This PR fixes a link in the README that points to the nuScenes basics tutorial.

Fix basic_tutorial name

---

python-sdk/nuscenes/lidarseg/lidarseg_utils.py
python-sdk/nuscenes/nuscenes.py

- Add functionality to `render_pointcloud_in_image` to automatically determine which lidarseg classes are present in a pointcloud projected onto an image.
Previously, if the user does not specify a filter which contains the classes he / she wishes to see, and does the following with `show_lidarseg_legend=True`:
```
sample_token = '6dabc0fb1df045558f802246dd186b3f'
nusc.render_pointcloud_in_image(sample_token,
pointsensor_channel='LIDAR_TOP',
camera_channel='CAM_BACK',
render_intensity=False,
show_lidarseg_labels=True,
render_if_no_points=False,
show_lidarseg_legend=True,
verbose=True)
```
Then the resulting visualization will be:
This is ugly as the legend fills almost the entire image, and the user is no longer able to view the projected pointcloud. The user will then have to manually …

Automatically determine which lidarseg classes are present in a pointcloud projected onto an image

---

python-sdk/nuscenes/lidarseg/lidarseg_utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- Flip ['CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT']  for aesthetic reasons
- Fix extra padding and axes appearing when rendering in notebook
- Enable `render_scene_with_pointclouds_for_all_cameras` to output frames as images
- Update indices used in the examples in tutorial

Improve aesthetics for render_scene_with_pointclouds_for_all_cameras

---

python-sdk/nuscenes/map_expansion/arcline_path_utils.py
python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/tutorials/map_expansion_tutorial.ipynb

- Automatically determine figure size: Figure size is either None (default setting, relative to canvas size), scalar (scales canvas size) or a tuple (manually specifies the size).
- Added render_connectivity method to show how to visualize the lanes and lane_connectors. See an example below:
- Fix bug with high discretization resolution for arcline paths. Previously the maximum possible `resolution_meters` that did not return an error was the minimum of the lengths of all paths in the map. Now it is simply clipped for each path if it exceeds the length.

Add render_centerlines method

---

python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- Remove the `render_if_no_points` argument from the relevant examples, and text
- Remove the section which discusses the functionality of the `render_if_no_points` argument

Remove render_if_no_points argument from lidarseg tutorial

---

python-sdk/nuscenes/nuscenes.py

- Enable loading of the categories from the same `category.json` for both nuScenes and nuScenes-lidarseg (nuScenes and nuScenes-lidarseg each had its own json for categories previously)
- Add an assertion to `render_scene_channel_lidarseg` and `render_scene_lidarseg` to check that the user's folder of lidarseg predictions exists

Single category.json for both nuScenes and nuScenes-lidarseg

---

python-sdk/nuscenes/utils/color_map.py

- Change the color of points for driveable surface to nuTonomy green

Use nuTonomy green for driveable surface

---

python-sdk/nuscenes/prediction/input_representation/utils.py

Update the documentation of the function "convert_to_pixel_coords" 
from 
:param resolution: Center of image.
to 
:param resolution: Resolution of image in pixels / meters.

Function documentation typo

---

python-sdk/nuscenes/scripts/export_poses.py

Update the script export_poses.py to correct variable name error. 'format' used instead of 'output_format'

Update the script export_poses.py

---

python-sdk/nuscenes/lidarseg/lidarseg_utils.py
python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/tests/test_lidarseg.py
python-sdk/nuscenes/utils/color_map.py
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

- Allow lidarseg stats to be sorted by count, name and index
- Allow users to display a legend for lidarseg with `render_sample_data`
- Improve the phrasing in the tutorial
- Add unit tests for lidarseg

Improve lidarseg rendering methods, update tutorial, add unit tests

---

docs/instructions_nuimages.md
docs/schema_nuimages.md
docs/schema_nuscenes.md
python-sdk/nuimages/nuimages.py
python-sdk/nuimages/scripts/render_images.py
python-sdk/nuimages/scripts/render_rare_classes.py
python-sdk/nuimages/tests/test_attributes.py
python-sdk/nuimages/tests/test_foreign_keys.py
python-sdk/nuimages/tests/test_overflow_bug.py
python-sdk/nuscenes/can_bus/README.md
python-sdk/nuscenes/eval/prediction/tests/test_metrics.py
python-sdk/nuscenes/prediction/input_representation/static_layers.py
python-sdk/nuscenes/prediction/tests/test_predict_helper.py
python-sdk/nuscenes/utils/map_mask.py
python-sdk/tutorials/nuimages_tutorial.ipynb

This PR makes the following changes:
- A unified script to render individual images or videos.
- Garbage collection when rendering lots of images.
- A function `find_corresponding_sample_data()` to find the matching lidar sample_data for a camera sample_data and vice versa.
- Fix existing tests and remove outputs from all tests.
- Sorting option in `list_categories()`.

nuImages videos

---

python-sdk/nuimages/nuimages.py
python-sdk/nuimages/scripts/render_images.py
python-sdk/nuimages/tests/test_overflow_bug.py
python-sdk/tutorials/nuimages_tutorial.ipynb

Updated render_depth method in sparse mode to overlay the points on the images.
This replaces https://github.com/nutonomy/nuscenes-devkit/pull/436, which was based on the wrong branch.
It also separates the sparse and dense depth rendering methods to have more flexibility.

Updated render_depth method (v2)

---

README.md
docs/installation.md
docs/instructions_nuimages.md
python-sdk/nuimages/nuimages.py
python-sdk/nuimages/utils/utils.py
python-sdk/tutorials/nuimages_tutorial.ipynb
setup/Dockerfile_3.6
setup/Dockerfile_3.7

- Update the documentation (tutorial, readme, installation.md, etc.) in nuImages
- Allow the user to adjust the font size in `render_image`
- Allow the user to render only surfaces, only objects, both, or neither in `render_image`
- Introduce a method `get_segmentation` to allow the user to get both the semantic segmentation mask and instance segmentation mask

Update nuImages documentation, add ability to get segmentation masks, improve listing and rendering functions

---

python-sdk/nuscenes/nuscenes.py
python-sdk/nuscenes/utils/color_map.py

- Re-order the colormap such that each class name is assigned an index by alphabetical order (except `noise` and `vehicle.ego`); the updated order of the classes will be:
```
noise
animal
human.pedestrian.adult
human.pedestrian.child
human.pedestrian.construction_worker
human.pedestrian.personal_mobility
human.pedestrian.police_officer
human.pedestrian.stroller
human.pedestrian.wheelchair
movable_object.barrier
movable_object.debris
movable_object.pushable_pullable
movable_object.trafficcone
static_object.bicycle_rack
vehicle.bicycle
vehicle.bus.bendy
vehicle.bus.rigid
vehicle.car
vehicle.construction
vehicle.emergency.ambulance
vehicle.emergency.police
vehicle.motorcycle
vehicle.trailer
vehicle.truck
flat.driveable_surface
flat.other
flat.sidewalk
flat.terrain
static.manmade
static.other …
```

Align indices in nuImages and nuScenes-lidarseg

---

python-sdk/nuimages/nuimages.py
python-sdk/nuscenes/can_bus/can_bus_api.py
python-sdk/nuscenes/map_expansion/map_api.py
python-sdk/tutorials/nuimages_tutorial.ipynb
python-sdk/tutorials/prediction_tutorial.ipynb

**nuImages:**
- Adds a new method `list_sample_data_histogram()`.
- Improves render_image settings to avoid font warning by default.
**nuScenes:**
- Fix issue where mark_inset sometimes shows just a filled black box.
- Minor formatting changes.

nuScenes 2.0 tutorial revamp

---

setup/setup.py

This PR updates the requirements for the pip package. Previously these were a flat list, now they are split into separate files which need to be parse individually.

nuScenes v2.0 pip requirements

---

python-sdk/tutorials/README.md
python-sdk/tutorials/nuimages_tutorial.ipynb
python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb
python-sdk/tutorials/nuscenes_tutorial.ipynb

- Update the nuScenes tutorials so that they can be run in Colab, if the user desires; as an example: https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/tutorial_colab/python-sdk/tutorials/nuscenes_tutorial.ipynb

nuScenes tutorials in Google Colab

---

docs/schema_nuimages.md

This addresses https://github.com/nutonomy/nuscenes-devkit/issues/471 by better documenting the order of the camera calibration coefficients in nuImages.

Specify the calibration coefficients in nuImages

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/lidarseg/evaluate.py
python-sdk/nuscenes/eval/lidarseg/utils.py
python-sdk/nuscenes/eval/lidarseg/validate_submission.py

- Introduce the evaluation code for the nuScenes-lidarseg challenge
- Introduce the accompanying utils for the evaluation code
- Add a script to allow users to validate their results folder before submission to the EvalAI server

Evaluation code for nuScenes-lidarseg challenge

---

python-sdk/nuimages/nuimages.py

This PR removes an assertion that was triggered for every image with an empty object mask. Since these are allowed, we should not throw an assertion.

nuImages: Remove broken assertion

---

python-sdk/nuscenes/eval/tracking/README.md

Replace the word "ratio" with "number" in the tracking readme.

Tracking readme - Replace ratio with number

---

docs/installation.md
python-sdk/nuscenes/eval/tracking/algo.py
python-sdk/nuscenes/eval/tracking/utils.py
python-sdk/nuscenes/map_expansion/tests/test_all_maps.py
python-sdk/nuscenes/prediction/tests/test_backbone.py
python-sdk/nuscenes/prediction/tests/test_covernet.py
python-sdk/nuscenes/prediction/tests/test_mtp.py
python-sdk/nuscenes/prediction/tests/test_mtp_loss.py
setup/requirements.txt

This PR removes the tracking and prediction requirements from the default nuscenes-devkit installation. They can still be installed manually. The major implication of this is that all unit test which require these packages *would* fail. We therefore catch `ModuleNotFoundErrors` when importing the modules `torch`, `motmetrics` and `pandas`.
Here is the test output *without* those requirements installed:
```
...........................ssss.............................................................................
----------------------------------------------------------------------
Ran 179 tests in 21.658s
```
Here is the test output *with* those requirements installed:
```
.................................................................................................................... …
```

Remove torch/motmetrics/pandas requirements and skip related tests

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

- Add a brief summary of the results of old challenges to create a record of who won which challenge (difficult to understand from the leaderboard).
- Extend the current submission deadline to start from November 1.
- Clarify that submission limits are per year.

Add legacy challenge results, clarify rules

---

python-sdk/nuscenes/eval/detection/README.md
python-sdk/nuscenes/eval/lidarseg/README.md
python-sdk/nuscenes/eval/prediction/README.md
python-sdk/nuscenes/eval/tracking/README.md

This PR adds information on which team won which award. This is to keep a public record of the past awards.

Add awards to challenges

---

python-sdk/nuscenes/eval/prediction/submission/do_inference.py
python-sdk/nuscenes/eval/tracking/algo.py
python-sdk/nuscenes/prediction/models/mtp.py
python-sdk/nuscenes/scripts/export_instance_videos.py
python-sdk/nuscenes/scripts/export_scene_videos.py

This PR improves the instance video script:
- Change the default codec to MPEG.
- Reformatting to align more with rest of the devkit.
- Adds type hints and resolves PEP issues.
Besides that it also fixes a big in a similar script when no out_dir is provided.

Refactor export instance video script

---

setup/setup.py

- Update version number for new pip package #534.
- Exclude commented out requirements to avoid errors in setup.py.

Fix setup.py, bump version to v.1.1.2

---

python-sdk/nuscenes/eval/prediction/README.md

Change the rules to allow 3 submissions per month, rather than per year.

Update prediction submission rules

---

setup/requirements/requirements_base.txt

The `nuscenes-devkit` package was using PIL version `<= 6.2.1` and for some reason PIL imports were breaking for that PIL version. In this PR, the `requirements.txt` is updated to ensure that the PIL version is `> 6.2.1`.

Specify PIL version to be > 6.2.1

---

python-sdk/nuscenes/utils/data_classes.py

As pointed out in https://forum.nuscenes.org/t/fusing-lidar-sweeps-with-keyframe/533/9, the functions `from_file_multisweep` and `from_file` in `LidarPointCloud` do not return a point cloud of the same dtype, but rather use float64 vs. float32. This means that the export_kitti script can run into problems when modified to use this function.
This PR fixes that by forcing `from_file_multisweep` to return a float32 array.

Fix multisweep dtype

---

python-sdk/nuscenes/eval/common/loaders.py

Currently the detection eval code has an import dependency on some of the tracking code. Hence, if the motmetrics package of the tracking code is not available, all third party unit tests that use the detection code will be skipped. This PR works around that by only importing the package inside the relevant function.

Avoid unittest skipping in detection eval

---

python-sdk/nuscenes/eval/detection/algo.py
setup/setup.py

- Bump pip version to 1.1.4 following previous changes to how tests work: https://github.com/nutonomy/nuscenes-devkit/commit/bfb57a4e5b044a9f448a3412b23966821f695aaf
- Replace legacy float format to avoid deprecation warnings in numpy

Pip package 1.1.4, replace legacy float format

---

README.md
setup/setup.py

- Bump the pip version for the nuscenes-devkit to `1.1.6`
- Extend the list of authors given the introduction of nuScenes-panoptic

Bump pip version to 1.1.6

---

python-sdk/nuscenes/prediction/helper.py

I got confused when using get_future_for_agent because there was no mention of the effect just_xy has on in_agent_frame, which is present for instance in get_past_for_agent

Adding missing precision about the relevancy of the `in_agent_frame` in the `Helper.get_future_for_agent` method

---

python-sdk/nuscenes/eval/common/loaders.py

- Update print statement in `filter_eval_boxes` to say that points-based filtering is done based on sum of lidar and radar points (see https://github.com/nutonomy/nuscenes-devkit/issues/625 for details)

Update print statement in filter_eval_boxes to say that points-based filtering is done based on sum of lidar and radar points

---

python-sdk/nuscenes/can_bus/README.md

This PR:
- Updates the (min, max) ranges for various CAN bus fields.
- Removes a reference to unrelated fields.

Correct CAN value ranges in readme, addresses #648

---

python-sdk/nuscenes/eval/panoptic/README.md
python-sdk/nuscenes/panoptic/generate_panoptic_labels.py

There is a bug in the panoptic labels generation. For these thing category points that not belongs to (inside) any annotated boxes, their values will be lidarseg * 1000 rather than the expected 0.  In panoptic evaluation, the impact is these pixels will be treated as an instance with instance_id = 0, panoptic class  = lidarseg class. This PR is to reset their panoptic labels to 0.

Panoptic labels generation fix

---

python-sdk/nuscenes/lidarseg/class_histogram.py

-  Extend the lidarseg plot to plot histograms for both number of points and number of scan-wise instances per class; the resulting plot is as follows:

 Extend lidarseg plot to plot histograms for both number of points and number of scan-wise instances per class

---

README.md
python-sdk/nuscenes/eval/panoptic/evaluate.py
python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py
setup/setup.py

Add PAT metric for panoptic tracking evaluation.

Added PAT metric

---

README.md
python-sdk/nuscenes/eval/tracking/configs/tracking_nips_2019.json
python-sdk/nuscenes/eval/tracking/constants.py
python-sdk/nuscenes/eval/tracking/data_classes.py
python-sdk/nuscenes/eval/tracking/evaluate.py
python-sdk/nuscenes/eval/tracking/render.py
python-sdk/nuscenes/eval/tracking/tests/test_evaluate.py
setup/setup.py

This PR moves the fields TRACKING_NAMES, PRETTY_TRACKING_NAMES and TRACKING_COLORS from constants.py to the config json file. This way users can use the tracking eval code on custom datasets with different classes.

Tracking_eval refactor

---

python-sdk/nuscenes/eval/tracking/algo.py

- Update the sanity check in algo.py for tracking evaluation due to different behavior of `np.unique` in `numpy<=1.18` and `numpy>1.1`. This should close #700  and #717

Update sanity check in algo.py for tracking evaluation due to different behavior of np.unique in numpy<=1.18 and numpy>1.18

---

python-sdk/nuscenes/prediction/models/covernet.py

After discussing this issue with [Erik Wolff](https://github.com/emwolff), he asked me to create a pull request with this slight change in order to add a non-linearity to the provided CoverNet model.

add ReLU activation function after each linear layer in CoverNet model

---

python-sdk/nuscenes/eval/prediction/baseline_model_inference.py

The data_root parameter is not passed when calling get_prediction_challenge_split().  
This PR does:
- Pass data_root to get_prediction_challenge_split() in [`baseline_model_inference.py`](https://github.com/nutonomy/nuscenes-devkit/pull/761/commits/4a7a96dee1e41155468de4fd8861eed79e4d9831#diff-19125fb7c15589b7e7d1973a99d008d04ff246c313e0b6e9aebaee9c14bb38ff)

Pass dataroot to get_prediction_challenge_split() in baseline_model_inference

---

setup/requirements/requirements_base.txt

Specify version for `matplotlib` and `shapely` in `requirements_base.txt`
This should address various issues, including #870, #863 and #861

Specify version for matplotlib and shapely in requirements_base.txt

---

python-sdk/nuimages/nuimages.py

resolve syntax warning for invalid string comparison
```
SyntaxWarning: "is not" with a literal. Did you mean "!="?
```

fix: resolve invalid string comparison

---

setup/requirements/requirements_base.txt

Add specification of `numpy>=1.22.0` related to https://github.com/nutonomy/nuscenes-devkit/issues/968

chore(deps): specify `numpy` and `opencv-python` version

---

setup/requirements/requirements_base.txt
setup/setup.py

Hello good afternoon thanks for your work in your project. 
We are having problem in our build system due to `nuscenes-devkit` pulling some unnecessary runtime dependencies. 
In particular we have found `jupyter` being particularly problematic. 
In this PR I'm doing the following:
- Set matplotlib <3.6.0 (the breaking change that caused [this issue](https://github.com/nutonomy/nuscenes-devkit/issues/861 was introduced in 3.6.0) 
- Set Shapely <2.0.0
- Remove `jupyter` as it is not a necessary runtime deps.

Improve runtime dependencies 

---

setup/requirements/requirements_base.txt

numpy 2.0.0 comes with some bigger changes that I think the nuscenes-devkit is not prepared for (there are even problems for larger minor versions within numpy 1 https://github.com/nutonomy/nuscenes-devkit/issues/1055)
So I believe, the best we can do right now to enable a smooth installation of requirements is to at least prevent numpy 2

Prevent numpy >= 2.0.0
